In [21]:
# Artificial Neural Network

# Installing Keras
# Enter the following command in a terminal (or anaconda prompt for Windows users): conda install -c conda-forge keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [22]:
tf.__version__

'2.1.0'

In [23]:
# Importing the dataset
dataset = pd.read_csv(r'C:\Users\akiper\Desktop\Machine Learning Course\Machine-Learning-A-Z-New\Machine Learning A-Z New\Part 8 - Deep Learning\Section 39 - Artificial Neural Networks (ANN)\Churn_Modelling.csv')
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [24]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [25]:
print(y)

[1 0 1 ... 1 1 0]


---

In [26]:
#Encoding Categorical Data

In [27]:
#Encoding the "Gender" Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:,2]) #Applying the encoding specifically to the Gender column in the X matrix

In [28]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [29]:
#Encoding the "Geography" Column
#Note: We have to use OneHot Encoding because there is no order of relationship between the countries (Gender is binary so regular encoding works there but not here)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [30]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


---

In [31]:
#Splitting the dataset into Traning and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [32]:
#Feature Scaling
#Note: Feature Scaling is REQUIRED for Deep Learning and building ANN's
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

---

In [33]:
#Building the ANN 

In [34]:
#Initializing the ANN
ann = tf.keras.models.Sequential()

In [35]:
#Adding the input layer and the 1st hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
#Dense class: Creates a fully connected layer
#Units is the number of hidden neurons want to have in connected layer

In [36]:
#Adding the 2nd layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) #Copy and Paste the previous cell's code to create another layer (i.e. this 2nd layer)

In [37]:
#Adding the Output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid')) #NOTE: when dealing with binary outcomes, you only need 1 unit; When dealing with non-binary outputs, then use the actual number of output choices
#NOTE: For output layer, you want to use the Sigmoid Activation Funciton bc it gives us the probablity that the outcome is accurate along with the predicted outcome

---

In [38]:
#Training the ANN

In [39]:
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [40]:
#Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 83us/sample - loss: 0.6565 - accuracy: 0.6237
Epoch 2/100
8000/8000 [==============================] - 0s 40us/sample - loss: 0.4779 - accuracy: 0.7994
Epoch 3/100
8000/8000 [==============================] - 0s 39us/sample - loss: 0.4327 - accuracy: 0.8114
Epoch 4/100
8000/8000 [==============================] - 0s 35us/sample - loss: 0.4132 - accuracy: 0.8170
Epoch 5/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3992 - accuracy: 0.8227
Epoch 6/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3872 - accuracy: 0.8324
Epoch 7/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3778 - accuracy: 0.8380
Epoch 8/100
8000/8000 [==============================] - 0s 34us/sample - loss: 0.3707 - accuracy: 0.8449
Epoch 9/100
8000/8000 [==============================] - 0s 35us/sample - loss: 0.3650 - accuracy: 0.8474
Epoch 10/100
8000/8000 [

---

In [ ]:
#Making predictions and evaluating the model

In [41]:
#Predicting the result of a single observation
print(ann.predict(x = sc_x.transform([[1,0,0,600,1,40,3, 60000, 2, 1, 1, 50000]])) > 0.5) #Note: use '>0.5' to change result from probablility to word result
#NOTE: With One Hot Encoding, you must separate the values with a comma even though they are not separated by a comma in the print result above
#NOTE: Remember, apply the predict method onto the scale/scaling used in feature scaling (i.e. use sc object from feature scaling section)

[[False]]


---

In [42]:
#Predicting the Test set Results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) #If y_pred < 0.5, then y pred will become 0 (False) and if y pred> 0.5, then y pred becomes 1 (True)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#On left is predicted outcome and right is actual outcome 

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [43]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
matrix = confusion_matrix(y_test, y_pred)
print(matrix)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 199  206]]


0.861